FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

COPY ./src/UserService/*.csproj ./UserService/
COPY ./src/Shared/*.csproj ./Shared/
WORKDIR /app/UserService
RUN dotnet restore

COPY ./src/UserService/. ./UserService/
COPY ./src/Shared/. ./Shared/
WORKDIR /app/UserService
RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /out ./

ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+:80

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost/health || exit 1

ENTRYPOINT ["dotnet", "UserService.dll"]